version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "3199:3199"
    volumes:
        - ./db:/microservice/db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app.logs
